// <auto-generated />
using System;
using AcmeCorpDraw.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeCorpDraw.WebApp.Migrations
{
    [DbContext(typeof(AcmeDbContext))]
    [Migration("20260217154941_AddSerialNumbers")]
    partial class AddSerialNumbers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcmeCorpDraw.Domain.Models.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "ACME-0JIE-XYX2-N0AT"
                        },
                        new
                        {
                            Id = 2,
                            Number = "ACME-0OIF-73CP-X5VS"
                        },
                        new
                        {
                            Id = 3,
                            Number = "ACME-0W6O-6ELF-XET8"
                        },
                        new
                        {
                            Id = 4,
                            Number = "ACME-0ZQP-X1SV-4MM1"
                        },
                        new
                        {
                            Id = 5,
                            Number = "ACME-21TB-AP2C-IJB2"
                        },
                        new
                        {
                            Id = 6,
                            Number = "ACME-2NOH-CMFO-XCR4"
                        },
                        new
                        {
                            Id = 7,
                            Number = "ACME-2OM6-B1M4-N9NF"
                        },
                        new
                        {
                            Id = 8,
                            Number = "ACME-2YNM-14T5-DY8P"
                        },
                        new
                        {
                            Id = 9,
                            Number = "ACME-3GPO-KOQL-YT6J"
                        },
                        new
                        {
                            Id = 10,
                            Number = "ACME-3PL4-EIQX-8K4Q"
                        },
                        new
                        {
                            Id = 11,
                            Number = "ACME-44YA-X9EL-ATXA"
                        },
                        new
                        {
                            Id = 12,
                            Number = "ACME-4P7H-PLHH-0G9U"
                        },
                        new
                        {
                            Id = 13,
                            Number = "ACME-60UN-FNY6-5IGD"
                        },
                        new
                        {
                            Id = 14,
                            Number = "ACME-6GIQ-BUDW-I8FL"
                        },
                        new
                        {
                            Id = 15,
                            Number = "ACME-6O0R-GLNH-H8RI"
                        },
                        new
                        {
                            Id = 16,
                            Number = "ACME-6OF2-L76M-4FFB"
                        },
                        new
                        {
                            Id = 17,
                            Number = "ACME-7JV9-ZD6H-9V9E"
                        },
                        new
                        {
                            Id = 18,
                            Number = "ACME-86OA-DWYV-97CF"
                        },
                        new
                        {
                            Id = 19,
                            Number = "ACME-86VT-UE7N-W2SG"
                        },
                        new
                        {
                            Id = 20,
                            Number = "ACME-96SP-IIUE-3HC0"
                        },
                        new
                        {
                            Id = 21,
                            Number = "ACME-AM44-21NZ-7BAO"
                        },
                        new
                        {
                            Id = 22,
                            Number = "ACME-ASNZ-FJPK-5WA9"
                        },
                        new
                        {
                            Id = 23,
                            Number = "ACME-B0J4-DWMP-AL4O"
                        },
                        new
                        {
                            Id = 24,
                            Number = "ACME-C0PV-G3VH-ZLK2"
                        },
                        new
                        {
                            Id = 25,
                            Number = "ACME-C5H4-FPH5-4EKE"
                        },
                        new
                        {
                            Id = 26,
                            Number = "ACME-CUHZ-AXUC-BQW3"
                        },
                        new
                        {
                            Id = 27,
                            Number = "ACME-D9SY-WYV3-4CK9"
                        },
                        new
                        {
                            Id = 28,
                            Number = "ACME-DR5A-XQDQ-THN6"
                        },
                        new
                        {
                            Id = 29,
                            Number = "ACME-EJ5C-BZSM-Y39Y"
                        },
                        new
                        {
                            Id = 30,
                            Number = "ACME-F114-083B-D7IV"
                        },
                        new
                        {
                            Id = 31,
                            Number = "ACME-FHTN-C2BI-XGMV"
                        },
                        new
                        {
                            Id = 32,
                            Number = "ACME-FHXC-6MO6-8XR8"
                        },
                        new
                        {
                            Id = 33,
                            Number = "ACME-FTBC-2DY7-HRVF"
                        },
                        new
                        {
                            Id = 34,
                            Number = "ACME-G513-DOS1-MXH7"
                        },
                        new
                        {
                            Id = 35,
                            Number = "ACME-GUEE-5W1N-XJV5"
                        },
                        new
                        {
                            Id = 36,
                            Number = "ACME-HDWP-3FEE-04XF"
                        },
                        new
                        {
                            Id = 37,
                            Number = "ACME-HITW-TRGO-J47R"
                        },
                        new
                        {
                            Id = 38,
                            Number = "ACME-HJZC-WJ29-LLX2"
                        },
                        new
                        {
                            Id = 39,
                            Number = "ACME-HTR4-WTQK-RLQM"
                        },
                        new
                        {
                            Id = 40,
                            Number = "ACME-HXR9-DZFK-22ZC"
                        },
                        new
                        {
                            Id = 41,
                            Number = "ACME-I8PX-UC9D-48TO"
                        },
                        new
                        {
                            Id = 42,
                            Number = "ACME-IM3S-MUHP-UOBE"
                        },
                        new
                        {
                            Id = 43,
                            Number = "ACME-IW1M-DCTN-QINF"
                        },
                        new
                        {
                            Id = 44,
                            Number = "ACME-IZQM-G76Z-TN98"
                        },
                        new
                        {
                            Id = 45,
                            Number = "ACME-JF69-LLRE-KRHP"
                        },
                        new
                        {
                            Id = 46,
                            Number = "ACME-JHMH-Y1SG-EM06"
                        },
                        new
                        {
                            Id = 47,
                            Number = "ACME-JPAU-A94S-YKTR"
                        },
                        new
                        {
                            Id = 48,
                            Number = "ACME-K87F-C8QH-4ZGD"
                        },
                        new
                        {
                            Id = 49,
                            Number = "ACME-KGDB-V5YQ-QC31"
                        },
                        new
                        {
                            Id = 50,
                            Number = "ACME-KN8Y-1XGM-6POY"
                        },
                        new
                        {
                            Id = 51,
                            Number = "ACME-KNW9-5O4G-PM6K"
                        },
                        new
                        {
                            Id = 52,
                            Number = "ACME-LP1C-WLZT-WIOA"
                        },
                        new
                        {
                            Id = 53,
                            Number = "ACME-M2F1-3YRX-R2B1"
                        },
                        new
                        {
                            Id = 54,
                            Number = "ACME-M8YP-XUFV-ZDFG"
                        },
                        new
                        {
                            Id = 55,
                            Number = "ACME-M9GA-HX36-FL15"
                        },
                        new
                        {
                            Id = 56,
                            Number = "ACME-MQTV-XHOT-L4R8"
                        },
                        new
                        {
                            Id = 57,
                            Number = "ACME-MTC6-0D9Z-IMO7"
                        },
                        new
                        {
                            Id = 58,
                            Number = "ACME-MU9Y-FHSN-8QSN"
                        },
                        new
                        {
                            Id = 59,
                            Number = "ACME-N2M5-JGLH-JEZY"
                        },
                        new
                        {
                            Id = 60,
                            Number = "ACME-NHTL-6K9X-YUS8"
                        },
                        new
                        {
                            Id = 61,
                            Number = "ACME-O31P-6CA2-TY64"
                        },
                        new
                        {
                            Id = 62,
                            Number = "ACME-OWBW-L1V6-IZKA"
                        },
                        new
                        {
                            Id = 63,
                            Number = "ACME-PL1O-JIVK-CS61"
                        },
                        new
                        {
                            Id = 64,
                            Number = "ACME-PU94-KWFI-KO0L"
                        },
                        new
                        {
                            Id = 65,
                            Number = "ACME-Q1KF-EMRT-XID5"
                        },
                        new
                        {
                            Id = 66,
                            Number = "ACME-Q5MG-SU8B-O5QY"
                        },
                        new
                        {
                            Id = 67,
                            Number = "ACME-QAXV-KCZ6-XW97"
                        },
                        new
                        {
                            Id = 68,
                            Number = "ACME-QIS9-O4TO-97TA"
                        },
                        new
                        {
                            Id = 69,
                            Number = "ACME-QPHX-56PT-TMED"
                        },
                        new
                        {
                            Id = 70,
                            Number = "ACME-R37Z-VW30-XJXW"
                        },
                        new
                        {
                            Id = 71,
                            Number = "ACME-RNP4-PN1C-LC76"
                        },
                        new
                        {
                            Id = 72,
                            Number = "ACME-RRRZ-Q67P-6JIS"
                        },
                        new
                        {
                            Id = 73,
                            Number = "ACME-SA00-1OY3-12S0"
                        },
                        new
                        {
                            Id = 74,
                            Number = "ACME-SBGD-PLXC-RCTQ"
                        },
                        new
                        {
                            Id = 75,
                            Number = "ACME-SOES-79ZN-KN0P"
                        },
                        new
                        {
                            Id = 76,
                            Number = "ACME-SOOV-UGVJ-CRH2"
                        },
                        new
                        {
                            Id = 77,
                            Number = "ACME-STZI-8E3P-LE17"
                        },
                        new
                        {
                            Id = 78,
                            Number = "ACME-T2QO-HC6T-EIYL"
                        },
                        new
                        {
                            Id = 79,
                            Number = "ACME-T8FT-9FPK-FYFK"
                        },
                        new
                        {
                            Id = 80,
                            Number = "ACME-TBM4-NYPV-2A6V"
                        },
                        new
                        {
                            Id = 81,
                            Number = "ACME-TP8S-59E3-TBNB"
                        },
                        new
                        {
                            Id = 82,
                            Number = "ACME-TS56-AEU9-YM0G"
                        },
                        new
                        {
                            Id = 83,
                            Number = "ACME-UKAR-1UFR-CBIL"
                        },
                        new
                        {
                            Id = 84,
                            Number = "ACME-VC9M-Q7EU-S9I2"
                        },
                        new
                        {
                            Id = 85,
                            Number = "ACME-VDKW-VMOH-OGXT"
                        },
                        new
                        {
                            Id = 86,
                            Number = "ACME-VMXB-8VDS-Q4DY"
                        },
                        new
                        {
                            Id = 87,
                            Number = "ACME-WWPK-0CMY-099N"
                        },
                        new
                        {
                            Id = 88,
                            Number = "ACME-X7UE-R0GR-NT21"
                        },
                        new
                        {
                            Id = 89,
                            Number = "ACME-X8JU-4DE9-AYSP"
                        },
                        new
                        {
                            Id = 90,
                            Number = "ACME-XKBL-SPUC-5FKA"
                        },
                        new
                        {
                            Id = 91,
                            Number = "ACME-XMHN-YJNO-FUKI"
                        },
                        new
                        {
                            Id = 92,
                            Number = "ACME-XMXY-A9Q9-OZ9C"
                        },
                        new
                        {
                            Id = 93,
                            Number = "ACME-Y9LU-6H7L-HLGX"
                        },
                        new
                        {
                            Id = 94,
                            Number = "ACME-YEUC-YVC9-BLEB"
                        },
                        new
                        {
                            Id = 95,
                            Number = "ACME-YQWV-6UFZ-P1ZE"
                        },
                        new
                        {
                            Id = 96,
                            Number = "ACME-Z3SB-FHBC-YTPB"
                        },
                        new
                        {
                            Id = 97,
                            Number = "ACME-Z4Y8-38KJ-HSH8"
                        },
                        new
                        {
                            Id = 98,
                            Number = "ACME-Z5KT-WTJL-R7U8"
                        },
                        new
                        {
                            Id = 99,
                            Number = "ACME-ZIQW-9E1H-5DAM"
                        },
                        new
                        {
                            Id = 100,
                            Number = "ACME-ZVMI-I92G-99YI"
                        });
                });

            modelBuilder.Entity("AcmeCorpDraw.Domain.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
